# Generated by Django 4.0.1 on 2022-06-05 19:09

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(null=True, upload_to=pathlib.PureWindowsPath('C:/Code/web/django/shareFile/CrossShare/media')),
        ),
    ]
