# Generated by Django 4.0.1 on 2022-06-12 18:37

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0004_alter_uploadfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to=pathlib.PureWindowsPath('C:/Code/web/django/shareFile/CrossShare/media')),
        ),
    ]
