# Generated by Django 4.0.1 on 2022-07-05 07:26

from django.db import migrations, models
import django.db.models.deletion
import pathlib
import uploadFile.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0006_uploadfile_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to=pathlib.PureWindowsPath('C:/Code/web/django/shareFile/CrossShare/public/media')),
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=uploadFile.models.upload_path)),
                ('created_at', models.DateField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadFile.folder')),
            ],
        ),
    ]
